config/routes.rb
Rails.application.routes.draw do

  get 'usuarios/pesquisar' => 'usuarios#pesquisar'
  
  resources :usuarios
  
  get 'posts' => 'posts#index'
  get 'posts/new' => 'posts#new'
  post 'posts' => 'posts#create'
  
  root 'home#index'

  get 'login' => 'login#index', as: :login_form

  post 'login/login', as: :login
  post 'login/logout', as: :logout
  
      

end

app/models/assunto.rb
class Assunto < ActiveRecord::Base
	#has_many :posts
	#has_many :assunto #string maior que 2 e menor que 20
	#has_many :tipo #GF e GU


#	validates :tipo,
#  			#email: true,
# 			presence: {message: 'O tipo de assunto deve ser preenchido'},
#  			length: {in: 1..2}


# 	validates :assunto,
  			#email: true,
 # 			presence: {message: 'O assunto deve ser preenchido'},
  #			length: { in: 2..25},
  #			uniqueness: {message: 'Esse assunto ja existe'}
 

end

app/models/nivel.rb
class Nivel < ActiveRecord::Base
	has_many:usuarios 
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :usuario
  belongs_to :assunto
end

app/models/usuario.rb
# encoding: UTF-8

class Usuario < ActiveRecord::Base
  belongs_to :nivel
  has_many :posts

  validates :nome,
  			#format: { with: /\A[a-zA-Z]+\z/ },???????
  			length: { in: 10..100 },#curto pq no html não passa de 100 já.. mas não funfou
  			presence: {message: 'O nome deve ser preenchido'}

  validates :email,
  			#email: true,
  			presence: {message: 'O email deve ser preenchido'},
  			length: { in: 5..140},
  			uniqueness: {message: 'Esse email já foi cadastrado'}
 
  validates :login,
  			presence: {message: 'O login deve ser preenchido'},
  			length: { in: 5..50},
  			uniqueness: {message: 'Esse login já foi cadastrado'}

  validates :senha,
        #:exclude => %w[ asdf qwert zxcv ]
  			length: { in: 5..32},
  			presence: {message: 'A senha deve ser preenchida'}

  validates :nascimento,
  			presence: {message: 'A data de nascimento é obrigatória'}

  validate :email_formatado

  private  
  def email_formatado
    if not email.blank?
      errors.add(:email, "Email inválido") unless email =~ /[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})/
    end
  end

end



#private
#  def data_nascimento_validacaoq2
#    errors.add :nascimento, ''
#  end
#como usar essa validaçao?
# class EmailValidator < ActiveModel::EachValidator
#   def validate_each(record, attribute, value)
#     unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
#       record.errors[attribute] << (options[:message] || "Não é um email")
#     end
#   end
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
end

app/controllers/geografia_controller.rb
class GeografiaController < ApplicationController
	
end

app/controllers/home_controller.rb
# encoding: UTF-8
class HomeController < ApplicationController
	def index
		
  	end

  def testando
  	render text: "teste, 1,2,3, teste som"
  end
end

app/controllers/login_controller.rb
#encoding: UTF-8
require 'digest'
class LoginController < ActionController::Base

	def index

	end

	def login
		u = Usuario.find_by_login_and_senha(params[:login], Digest::MD5.hexdigest(params[:senha]))
		if u.nil?
			flash[:error] = 'Nome ou senha inválidos' #flash não aparece
			render :index
		else
			session[:usuario] = u.nome
			redirect_to root_path, notice: 'Logado com sucesso' #notice não aparece
		end
		#redirect_to :usuarios
		#render text: 'Oi mundo'
		# if @usuario = Usuario.find_by_login(params[:login])
		# 	if @usuario.senha == (params[:senha])
		# 		render text:'colocar usuario na sesion e mandar para home'
		
		# 	else
		# 		render text:'erro de senha errada'
		# 	end
		# else
		# 	render text: 'erro de usuario inexistente'
		# end
	end

	def logout
		reset_session
		redirect_to root_path, notice: 'Você foi deslogado'
	end
end

app/controllers/posts_controller.rb
# encoding: UTF-8
class PostsController < ApplicationController
	#before_action :set_aluno, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	
	def new
		@post = Post.new()
	end

	def create
		usuario = Usuario.first #Usuario.new('Luiza Maria','luiza.kkkk@gmail.com','luizakkkk','lailai', '02-01-1997')
		#assunto = Assunto.find(params[:])
    	@post = Post.new(params.require(:post).permit(:conteudo, :tipo))
    	assunto = Assunto.new(params.require(:post).permit(:assunto))
    
    	
    	@post.data = DateTime.now()
    	
    	@post.usuario = usuario
    	@post.assunto = assunto
    	#@post.assunto = assunto
    	if @post.save
    		redirect_to :posts, notice: "#{@post.conteudo} inserido com sucesso" #não ta aparecendo
    	else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      		render :new
    	end
  	end

  	def destroy
  		u = Usuario.find params[:id]
  		u.destroy
  		redirect_to :usuarios, notice: "usuario #{u.nome} excluido"
	end

	def pesquisar
		@usuarios = Usuario.where("nome like '%#{params[:pesquisa]}%'")
		render :index
	end
end

app/controllers/usuarios_controller.rb
# encoding: UTF-8
require 'digest'

class UsuariosController < ApplicationController
	#before_action :set_aluno, only: [:show, :edit, :update, :destroy]

	def index
		@usuarios = Usuario.all
	end

	def show
		@usuario = Usuario.find(params[:id])
	end

	def edit
		@usuario = Usuario.find(params[:id])
	end

	def update
		@usuario = Usuario.find(params[:id])
		if @usuario.update(params.require(:usuario).permit(:nome, :email, :login, :nascimento, :senha))
			redirect_to :usuarios, notice: "#{@usuario.nome} atualizado com sucesso" #não ta aparecendo
    	else
      		render :edit
		end
	end

	def new
		@usuario = Usuario.new()
	end

	def create
    	@usuario = Usuario.new(params.require(:usuario).permit(:nome, :email, :login, :nascimento, :senha))
    	@usuario.senha = Digest::MD5.hexdigest(@usuario.senha)

    	if @usuario.save
    		redirect_to :usuarios, notice: "#{@usuario.nome} cadastrado com sucesso" #não ta aparecendo
    	else
      # This line overrides the default rendering behavior, which
      # would have been to render the "create" view.
      		render :new
    	end
  	end

  	def destroy
  		u = Usuario.find params[:id]
  		u.destroy
  		redirect_to :usuarios, notice: "usuario #{u.nome} excluido"
	end

	def pesquisar
		@usuarios = Usuario.where("nome like '%#{params[:pesquisa]}%'")
		render :index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/geografia_helper.rb
module GeografiaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/home/index.html.erb
<% if session[:usuario] %>

  Logado como  <%= session[:usuario] %>

  <%= form_tag({controller: 'login', action: 'logout'}) do %>
      <button>Logout</button>
  <% end %>
<% end %>

<div class="mask">
    <div class="header">
           <h2> Fórum geografia </h2>
           
  </div> 
    <div class="colleft">
          
      <div class="col1">
          <br><br><br><br><br><br><br><br><br>
          <%= link_to "Geografia Fisica"%>
          <br><br><br><br><br><br><br><br><br>
          </div>
      <div class="col2">
      <br><br><br><br><br><br><br><br><br>
           <%= link_to "Geografia humana"%>
      <br><br><br><br><br><br><br><br><br>
      </div> 
  </div>
      <div class="footer">
        <h1><%= link_to "Cadastrar usuario", new_usuario_path %> <h1>
      </div>
    
    </div>


    
	
        
      
  
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum Geografia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

	

</head>
<body>
	
	<%= yield %>

</body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ForumGeografia" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>


    <div class="container">

    <%= bootstrap_flash %>
    <%= yield %>
    
    </div> <!-- /container -->

  </body>
</html>

app/views/login/index.html.erb
<%= form_tag({action: 'login'}, class: 'form-signin', method: 'post') do %> 
<form class="form-signin" role="form">
	<h2 class="form-signin-heading">Login do Usuário</h2>
	<input type="text" name="login" class="form-control" placeholder="Login do usuario" required autofocus>
	<input type="password" name="senha" class="form-control" placeholder="Senha" required>
	<button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
</form>
<% end %>

app/views/posts/index.html.erb
<h3> Posts </h3>




<table>
  <thead>
    <tr>
      <th>Conteúdo</th>
      <th>Postado por:</th>
      <th>Em:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.conteudo %></td>
        <td><%= post.usuario.nome %></td>
        <td><%= post.data %></td>

      </tr>
    <% end %>
  </tbody> 
</table>

<p>

app/views/posts/new.html.erb
<h2>Novo Post</h2>

    

    <%= form_for @post do |f| %>

       <%= f.label 'Conteúdo:' %>
        <%= f.text_field :conteudo, maxlength: 10000, size: "600x120" %>

        </p>

        
        <%= f.select :assunto, ([["globalização", "0"], ["rochas", "1"]])%>

		</p>

        <%= f.label 'Outro assunto:' %> <font color="red">*Se vocẽ não achou nenhum assunto que se enquadre no seu post fique a vontade para cadastrar um novo.</font>
  
 

        <%= radio_button_tag(:tipo, "true") %>
		<%= label_tag(:geofis, "Geografia Física") %>
		<%= radio_button_tag(:tipo, "false") %>
		<%= label_tag(:geopol, "Geografia Política") %>

        
	</p>





    <%= f.submit 'Salvar' %>


<% end %>

app/views/usuarios/edit.html.erb

<h2>Editar Usuario</h2>

    <% if @usuario.errors.any? %>

        <% @usuario.errors.full_messages.each do |m| %>

            <%= m %>

        <% end %>
    <% end %>


    <%= form_for @usuario do |f| %>

       <%= f.label 'Nome:' %>
        <%= f.text_field :nome, maxlength: 100, size: "60x12" %>

        <p>
        <%= f.label 'E-mail:' %>
        <%= f.email_field :email, maxlength: 140, size: "60x12" %>
        </p>

        <p>
        <%= f.label 'Login:' %>
        <%= f.text_field :login, maxlength: 50, size: "30x6" %>
        </p>

        <p>
        <%= f.label 'Senha:' %>
        <%= f.password_field :senha, maxlength: 15, size: "15x3" %>
        </p>

        <%= f.label 'Nascimento:' %>
        <%= f.date_field :nascimento %>
        </p>


    <%= f.submit 'Salvar' %>


<% end %>

app/views/usuarios/index.html.erb
<h3> Usuarios </h3>


<%= link_to "Cadastrar", new_usuario_path %>

<table>
  <thead>
    <tr>
      <th>Nome completo</th>
      <th>Nome de usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.login %></td>
         <td><%= link_to 'Mostra', usuario %></td>
         <td><%= link_to 'Edita', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Excluir', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody> 
</table>

<p>

<form method="get" action='usuarios/pesquisar'>
Pesquisa de usuarios por nome: 
<input type="text" name="pesquisa" maxlength="100" size="60x12">

<input type="submit" value="Pesquisar">
</form>


app/views/usuarios/new.html.erb
<h2>Novo Usuario</h2>

    <% if @usuario.errors.any? %>

        <% @usuario.errors.full_messages.each do |m| %>

            <%= m %>

        <% end %>
    <% end %>


    <%= form_for @usuario do |f| %>

       <%= f.label 'Nome:' %>
        <%= f.text_field :nome, maxlength: 100, size: "60x12" %>

        <p>
        <%= f.label 'E-mail:' %>
        <%= f.email_field :email, maxlength: 140, size: "60x12" %>
        </p>

        <p>
        <%= f.label 'Login:' %>
        <%= f.text_field :login, maxlength: 50, size: "30x6" %>
        </p>

        <p>
        <%= f.label 'Senha:' %>
        <%= f.password_field :senha, maxlength: 15, size: "15x3" %>
        </p>

        <%= f.label 'Nascimento:' %>
        <%= f.date_field :nascimento %>
        </p>


    <%= f.submit 'Salvar' %>


<% end %>

app/views/usuarios/show.html.erb
<h3>Usuario: <%= @usuario.nome %> </h3>
<h4>Nome de usuário: <%= @usuario.login %> </h4>
<h4>Data de nascimento: <%= @usuario.nascimento %> </h4>
<h4>E-mail: <%= @usuario.email %> </h4>
